version: 2

jobs:
  bundle_dependencies:
    working_directory: ~/circleci-skywrath
    docker:
      - image: circleci/ruby:2.4.2-node
      - image: circleci/postgres:9.6-alpine
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-skywrath
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: - v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/circleci-skywrath/vendor/bundle
      - persist_to_workspace:
          root: .
          paths: vendor/bundle

workflows:
  version: 2
  build-and-test:
    jobs:
      - bundle_dependencies

# jobs:
#   build:
#     working_directory: ~/circleci-skywrath
#     docker:
#       - image: circleci/ruby:2.4.2-node
#       - image: circleci/postgres:9.6-alpine
#       - image: selenium/standalone-chrome:latest
#       - image: redis:latest
#     steps:
#       - checkout
#
#       - restore_cache:
#           keys:
#             - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
#             - gem-cache-{{ arch }}-{{ .Branch }}
#             - gem-cache
#
#       - run: bundle install --path vendor/bundle
#
#       - save_cache:
#           key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
#           paths:
#             - vendor/bundle
#
#       - restore_cache:
#           keys:
#             - yarn-cache-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
#             - yarn-cache-{{ arch }}-{{ .Branch }}
#             - yarn-cache
#
#       - run: yarn install
#
#       - save_cache:
#           key: yarn-cache-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
#           paths:
#             - node_modules
#
#       # Database setup
#       - run: bundle exec rake db:create
#       - run: bundle exec rake db:schema:load
#
#       # Run tests
#       - run: bundle exec rspec
#       - run: bundle exec spinach
#       - run: bundle exec rubocop
