export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAILURE = 'FETCH_FAILURE'

export const ASSIGN_REQUEST = 'ASSIGN_REQUEST'
export const ASSIGN_SUCCESS = 'ASSIGN_SUCCESS'
export const ASSIGN_FAILURE = 'ASSIGN_FAILURE'
