export FETCH_REQUEST = "alerts/FETCH_REQUEST"
export FETCH_SUCCESS = "alerts/FETCH_SUCCESS"
export FETCH_FAILURE = "alerts/FETCH_FAILURE"

export CREATE_REQUEST = "alerts/CREATE_REQUEST"
export CREATE_SUCCESS = "alerts/CREATE_SUCCESS"
export CREATE_FAILURE = "alerts/CREATE_FAILURE"
export CREATE_RESET = "alerts/CREATE_RESET"

export STATE_CHANGE_REQUEST = "alerts/STATE_CHANGE_REQUEST"
export STATE_CHANGE_SUCCESS = "alerts/STATE_CHANGE_SUCCESS"
export STATE_CHANGE_FAILURE = "alerts/STATE_CHANGE_FAILURE"
