export FETCH_REQUEST = "alerts/FETCH_REQUEST"
export FETCH_SUCCESS = "alerts/FETCH_SUCCESS"
export FETCH_FAILURE = "alerts/FETCH_FAILURE"

export CREATE_REQUEST = "alerts/CREATE_REQUEST"
export CREATE_SUCCESS = "alerts/CREATE_SUCCESS"
export CREATE_FAILURE = "alerts/CREATE_FAILURE"
export CREATE_RESET = "alerts/CREATE_RESET"

export CLOSE_REQUEST = "alerts/CLOSE_REQUEST"
export CLOSE_SUCCESS = "alerts/CLOSE_SUCCESS"
export CLOSE_FAILURE = "alerts/CLOSE_FAILURE"

export ASSIGN_REQUEST = "alerts/ASSIGN_REQUEST"
export ASSIGN_SUCCESS = "alerts/ASSIGN_SUCCESS"
export ASSIGN_FAILURE = "alerts/ASSIGN_FAILURE"
